Klimakhovich - first hometask
AlexOreshkevich/M-JC1-83-21 pull request #4
Opened 2021-08-06 09:47 UTC by Vladonblch

2021-08-06 09:54 UTC, Vladonblch commented
@AlexOreshkevich please review

2021-08-06 10:05 UTC, AlexOreshkevich requested changes
Please provide unit test and other changes according to our voice conversation

2021-08-08 07:01 UTC, AlexOreshkevich commented on app/src/main/java/by/academy/jc/klimakhovich/MyClass.java
> +
Nit-picky: unnecessary blank lines

2021-08-08 07:02 UTC, AlexOreshkevich commented on app/src/test/java/by/academy/jc/klimakhovich/TestMyClass.java
> +        assertNotNull(classUnderTest.greeting(), "MyClass should have a greeting");
I was asking for strong checks, like `assertEquals(expected, actual)`.

2021-08-08 07:04 UTC, AlexOreshkevich commented on app/src/test/java/by/academy/jc/klimakhovich/TestMyClass.java
> +        MyClass classUnderTest = new MyClass();
Store `classUnderTest` variable as a unit class property and initialize it in some of the two `@Before` clauses available.

2021-08-08 07:04 UTC, AlexOreshkevich approved these changes
lgtm

2021-08-10 09:29 UTC, closed without merging